name: Malvinas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4  
  charts_flutter:
  cloud_firestore: ^3.1.6
  flutter_launcher_icons: 
  firebase_auth: 
  animated_text_kit: ^4.2.1
 

 

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/img/launcher_icon.png"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^1.11.0
  #firebase_core: ^1.11.0

#dev_dependencies:
 # flutter_test:
  
  #  sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/img/juanita3p.jpg
     - assets/img/Jacar_Black.jpg
     - assets/img/Jacar.jpg
     - assets/img/Juanita.jpg
     - assets/img/Leontina_Zafira.jpg
     - assets/img/femme.png
     - assets/img/malvinas.png
     - assets/img/tabla.jpg
     - assets/img/launcher_icon.png
     - assets/img/Chaqueta_Abierta.jpg
     - assets/img/leontina_pink_camo.png 
     - assets/img/Namibia3Piezas.jpg
     - assets/img/fondo.jpg

     #Hombre
     - assets/img/hombre/BiColorGrisyFucsia.jpg 
     - assets/img/hombre/BostonClasic.png
     - assets/img/hombre/ChaquetaAbierta.png 
     - assets/img/hombre/ChaquetaCheff.png
     - assets/img/hombre/CombinadoTelaVerano.jpg
     - assets/img/hombre/Donato.png
     - assets/img/hombre/DonatoBlue.jpg
     - assets/img/hombre/Ema.png
     - assets/img/hombre/EmaCyan.jpg
     - assets/img/hombre/ChaquetaAbierta.png
     - assets/img/hombre/ChaquetaCheff.png
     #Mujer Arciel
     - assets/img/Mujer_Arciel/Clasico_Coral.png
     - assets/img/Mujer_Arciel/Clasico_Duo.jpg
     - assets/img/Mujer_Arciel/Juanita_Grey.jpg
     - assets/img/Mujer_Arciel/Leontina_Adela.jpg
     - assets/img/Mujer_Arciel/Leontina_Light_Green.jpg
     - assets/img/Mujer_Arciel/Leontina_Light_Pink.jpg
     - assets/img/Mujer_Arciel/Leontina_Total_Black.jpg
     - assets/img/Mujer_Arciel/Leontina_Zafira_Grey.jpg
     - assets/img/Mujer_Arciel/Paris.png
     - assets/img/Mujer_Arciel/Pediatrico.png
     - assets/img/Mujer_Arciel/Profesional.png
     - assets/img/Mujer_Arciel/Teodora_Blue.jpg
     - assets/img/Mujer_Arciel/Teodora_Carmin.jpg
     - assets/img/Mujer_Arciel/Teodora.png
     - assets/img/Mujer_Arciel/Teodora_Paris.png
     - assets/img/Mujer_Arciel/Arizona.jpg
     - assets/img/Mujer_Arciel/Juanita_Izzie.jpg
     #Arciel Mujer 3p
     - assets/img/Mujer_Arciel/Arciel_3p/Coral3p.jpg
     - assets/img/Mujer_Arciel/Arciel_3p/Femme3.jpg
     - assets/img/Mujer_Arciel/Arciel_3p/Juanita_Calli3p.png
     - assets/img/Mujer_Arciel/Arciel_3p/Malva3p.jpg
     - assets/img/Mujer_Arciel/Arciel_3p/Murphy3p.jpg
     - assets/img/Mujer_Arciel/Arciel_3p/Oslo3p.jpeg
     - assets/img/Mujer_Arciel/Arciel_3p/Paris3p.jpg
     


     
     
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Monserrat
       fonts:
         - asset: fonts/Montserrat-Regular.otf

     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Regular.ttf
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
